# Spring application name
spring:
  application:  
    name: gateway-service
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

# Register With Eureka
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
#    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# HTTP Port
server:
  port: 9900
  
# Microservices Paths
zuul:
  routes:
    user-service: 
      path: /user-service/**
      serviceId: user-service
      stripPrefix: true
    product-service: 
      path: /product-service/**
      serviceId: product-service
      stripPrefix: true
  ignoredServices: '*'
  sensitive-headers: 
#  prefix: /ms
  host:
    time-to-live: -1
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500

# Hystix configuration
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

# Ribbin configuration    
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 15000
      
 
