# Message used in application
app:
  message: 
    resource-not-found: 'Resource not found'
    user-not-found: 'User not found'
    image-not-found: 'Image not found'
    product-not-found: 'Product not found'
    category-not-found: 'Category not found'
    parent-category-not-found: 'Parent Category not found'
    