# Spring application
spring:
  application:
    name: common-lib
    
# MySQL Datasource configuration 
  datasource: 
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
# File Upload Directory
file:
  upload:
    baseDir: uploads