# MySQL Datasource configuration
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/cartservicedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
# File Upload Configuration  
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
      
# File Upload Directory
file:
  upload:
    dir: uploads
      
# Register with Eureka   
eureka: 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

# HTTP Port
server:
  port: 8083
  
# Logging
logging:
  level:
    root: ERROR
    com.shyam.api.userservice: ERROR
  path: /var/logs
  file:
    name: ${logging.path}/cartservice.log